const SOUND_FILES = [
  { file: "taktoseasizabiju.mp3", title: "Tak to se asi zabiju" },
  { file: "servus.mp3", title: "Servus" },
  { file: "ahojahoj.mp3", title: "Ahoj ahoj" },
  { file: "jasemzlejondra.mp3", title: "Já jsem zlej Ondra" },
  { file: "asirejze.mp3", title: "Asi rejže" },
  { file: "neuveritecosemistalo.mp3", title: "Neuvěříte, co se mi stalo" },
  { file: "alenotakstrejdo.mp3", title: "Ale no tak, strejdo" },
  { file: "heslo1.mp3", title: "Heslo" },
  { file: "jezkovytygrihoci.mp3", title: "Ježkovy tygří voči" },
  { file: "tymastedatrakar.mp3", title: "Ty máš teda trakař" },
  { file: "kdyzsekouknunasebe.mp3", title: "Když se kouknu na sebe" },
  { file: "poznaspodlecucu.mp3", title: "Poznáš podle čůču" },
  { file: "mnetonevadi.mp3", title: "Mně to nevadí" },
  { file: "tysesnunez.mp3", title: "Ty seš ňuňez" },
  { file: "caus.mp3", title: "čaus" },
  { file: "avysledek.mp3", title: "A výsledek" },
  { file: "tenorinezpivejtetotakpriteplene.mp3", title: "tenoři, nezpívejte to tak přitepleně" },
  { file: "nozdar.mp3", title: "No zdar" },
  { file: "cojefurt.mp3", title: "Co je furt" },
  { file: "prosimtetobudezadarmo.mp3", title: "Prosím tě, to bude zadarmo" },
  { file: "naschle.mp3", title: "Naschle" },
  { file: "pandaviduznemuze.mp3", title: "Pan David už nemůže" },
  { file: "heleuklidnisejo.mp3", title: "Hele, uklidni se, jo" },
  { file: "velrybajzna.mp3", title: "velrybajzna" },
  { file: "vitajte.mp3", title: "Vitajte" },
  { file: "anoanoanooterviajisedejiny.mp3", title: "ano ano ano" },
  { file: "ororokorebuk.mp3", title: "Ororokorebuk" },
  { file: "jatenhlehumorvubecnezvaldam.mp3", title: "Já tenhle humor vůbec nezvládám" },
  { file: "nahoda.mp3", title: "Náhoda" },
  { file: "nazle.mp3", title: "Nazle" },
  { file: "takzelitvinov.mp3", title: "Takže Litvínov" },
  { file: "atojetvujpripad.mp3", title: "A to je tvůj případ" },
  { file: "milanetadymilos.mp3", title: "Milane, tady Miloš" },
  { file: "caukrasavce.mp3", title: "Čau krasavče" },
  { file: "No stalo sa v regionech.mp3", title: "No stalo sa v regionech" },
  { file: "hmmmm.mp3", title: "Hmmmm" },
  { file: "namvladnekralmajmenoheroin.mp3", title: "Nám vládne král, má jméno heroin" },
  { file: "achohojjea.mp3", title: "achohojjea" },
  { file: "apak.mp3", title: "A pak" },
  { file: "taktyvole.mp3", title: "Tak ty vole" },
  { file: "huhuaaa.mp3", title: "Huhuaaa" },
  { file: "ukazpicu.mp3", title: "Ukaž píču" },
  { file: "nemamcas2.mp3", title: "Nemám čas 2" },
  { file: "nemamcas copy.mp3", title: "Nemám čas" },
  { file: "kamaradezdar.mp3", title: "Kamaráde, zdar" },
  { file: "tojezouzel.mp3", title: "To je zouzel" },
  { file: "nozdaar.mp3", title: "No zdáár" },
  { file: "zalezzpatkydogala.mp3", title: "Zalez zpátky do Gala" },
  { file: "atvujdeda.mp3", title: "A tvůj děda" },
  { file: "tysesvul.mp3", title: "Ty seš vůl" },
  { file: "tonejdezvonku.mp3", title: "To nejde zvonku" },
  { file: "bilaben.mp3", title: "bill a ben" },
  { file: "pikouamiladou.mp3", title: "Pikou a Miladou" },
  { file: "houbyklika.mp3", title: "Houby klika" },
  { file: "sinejakejhloupejne.mp3", title: "Jsi nějakej hloupej, ne?" },
  { file: "takstrejdo.mp3", title: "Tak strejdo" },
  { file: "nesmies1.mp3", title: "Nesmieš" },
  { file: "didoprdelebaumane.mp3", title: "Di do prdele, Baumane" },
  { file: "Nebojsespolutozvladneme.mp3", title: "Neboj se, spolu to zvládneme" },
  { file: "Valime.mp3", title: "Valíme" },
  { file: "jenomysemame.mp3", title: "Jé, no my se máme" },
  { file: "dobydendobyden.mp3", title: "Dobrý den, dobrý den" },
  { file: "nodobyden.mp3", title: "No, dobrý den" },
  { file: "tojeoslava.mp3", title: "To je oslava" },
  { file: "houbynen.mp3", title: "houbynen" },
  { file: "jezistadytosmrdi.mp3", title: "Ježiš, tady to smrdí" },
  { file: "rozlouceni.mp3", title: "Rozloučení" },
  { file: "kambysjezdil.mp3", title: "Kam bys jezdil" },
  { file: "nikamnejdu.mp3", title: "Nikam nejdu" },
  { file: "baha.mp3", title: "Baha" },
  { file: "tojehovez.mp3", title: "To je hověz" },
  { file: "tysifaktloupak.mp3", title: "Ty jsi fakt loupák" }
];